on:
  push:
    branches:
      - main

name: Build My Apps

jobs:
  build:
    name: Build and Release new apk
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Cache Flutter dependencies
      - name: Cache Flutter packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: flutter-packages-${{ runner.os }}-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            flutter-packages-${{ runner.os }}-

      # Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Setup Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode >android/app/mykey.jks

      - name: Setup key.properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=mykey.jks" >> android/key.properties

      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v2.0.9.2
          token: ${{ secrets.TOKEN }}
          name: "beta-v2.0.9.2"
          body: |
            ## What's New in v2.0.9.2
            
            - Improved Error Handlers.
            - **Redis Cloud Implementation and Fetching in Beta Phase**
            - **Structure of Redis added to Clean Architecture
            - **Added Redis-base to support syncfusion**
            - **Fixed Performance and Responsiveness Issues by Improvised BLoC Structure.
            - **New Feature**: Implemented Syncfusion and Redis for low latency.
            
            ### Known Issues are Resolved - Looking for vulnerabilities before Redis Full-Integration.
