on:
  push:
    branches:
      - main

name: Build My Apps

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode >mykey.jks

      - name: Setup key.properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=android/app/mykey.jks" >> android/key.properties

      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v2.0.5
          token: ${{ secrets.TOKEN }}
          name: "stable-v2.0.5"
          body: |
            ## What's New in v2.0.5
            
            - **New Feature**: Fast Login with Oauth2 independent of Firebase.
            - **Bug Fixes**: Resolved major bugs pertaining to memory leaks & getting ready for syncfusion.
            - **Performance Improvements**: Optimized the load response times.
            - **UI Enhancements**: Updated the home UI and added more animations.
            
            ### Known Issues
            - Some devices may still experience song player issues, will be solved in future releases .           
