on:
  push:
    branches:
      - main

name: Build My Apps

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v2.0.3
          token: ${{ secrets.TOKEN }}
          release_name: "stable-build-v2"
          body: |
            ## What's New in v2.0.3
            - **Bug Fixes**: Resolved an issue where all three quotes would display at the same time.
            - **Performance Improvements**: Optimized API response times.
            - **UI Enhancements**: Updated the home UI and improved navigation for a smoother experience.
            
            ### Known Issues
            - Some devices may still experience intermittent (API LOSSES) connectivity issues. We are investigating this.           
